package POJOS;
// Generated 14-may-2024 13:39:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Equipos generated by hbm2java
 */
public class Equipos  implements java.io.Serializable {


     private String codEquipo;
     private String nombre;
     private String localidad;
     private Set partidosesForCodVisitante = new HashSet(0);
     private Set partidosesForCodLocal = new HashSet(0);

    public Equipos() {
    }

	
    public Equipos(String codEquipo, String nombre) {
        this.codEquipo = codEquipo;
        this.nombre = nombre;
    }
    public Equipos(String codEquipo, String nombre, String localidad, Set partidosesForCodVisitante, Set partidosesForCodLocal) {
       this.codEquipo = codEquipo;
       this.nombre = nombre;
       this.localidad = localidad;
       this.partidosesForCodVisitante = partidosesForCodVisitante;
       this.partidosesForCodLocal = partidosesForCodLocal;
    }
   
    public String getCodEquipo() {
        return this.codEquipo;
    }
    
    public void setCodEquipo(String codEquipo) {
        this.codEquipo = codEquipo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }
    public Set getPartidosesForCodVisitante() {
        return this.partidosesForCodVisitante;
    }
    
    public void setPartidosesForCodVisitante(Set partidosesForCodVisitante) {
        this.partidosesForCodVisitante = partidosesForCodVisitante;
    }
    public Set getPartidosesForCodLocal() {
        return this.partidosesForCodLocal;
    }
    
    public void setPartidosesForCodLocal(Set partidosesForCodLocal) {
        this.partidosesForCodLocal = partidosesForCodLocal;
    }

    @Override
    public String toString() {
        return "Equipos{" + "codEquipo=" + codEquipo + ", nombre=" + nombre + ", localidad=" + localidad + '}';
    }

 

}


