package POJOS;
// Generated 11-may-2024 14:48:12 by Hibernate Tools 4.3.1



/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private String empNo;
     private Departamento departamento;
     private String nombre;
     private Integer salario;

    public Empleado() {
    }

	
    public Empleado(String empNo, Departamento departamento) {
        this.empNo = empNo;
        this.departamento = departamento;
    }
    public Empleado(String empNo, Departamento departamento, String nombre, Integer salario) {
       this.empNo = empNo;
       this.departamento = departamento;
       this.nombre = nombre;
       this.salario = salario;
    }
   
    public String getEmpNo() {
        return this.empNo;
    }
    
    public void setEmpNo(String empNo) {
        this.empNo = empNo;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getSalario() {
        return this.salario;
    }
    
    public void setSalario(Integer salario) {
        this.salario = salario;
    }

    @Override
    public String toString() {
        return "Empleado{" + "empNo=" + empNo + ", departamento=" + departamento.getNombre() + ", nombre=" + nombre + ", salario=" + salario + '}';
    }




}


