package POJOS;
// Generated 11-may-2024 14:48:12 by Hibernate Tools 4.3.1



/**
 * Retenciones generated by hbm2java
 */
public class Retenciones  implements java.io.Serializable {


     private RetencionesId id;
     private double salarioBruto;
     private double retencion;
     private double salarioNeto;

    public Retenciones() {
    }

    public Retenciones(RetencionesId id, double salarioBruto, double retencion, double salarioNeto) {
       this.id = id;
       this.salarioBruto = salarioBruto;
       this.retencion = retencion;
       this.salarioNeto = salarioNeto;
    }
   
    public RetencionesId getId() {
        return this.id;
    }
    
    public void setId(RetencionesId id) {
        this.id = id;
    }
    public double getSalarioBruto() {
        return this.salarioBruto;
    }
    
    public void setSalarioBruto(double salarioBruto) {
        this.salarioBruto = salarioBruto;
    }
    public double getRetencion() {
        return this.retencion;
    }
    
    public void setRetencion(double retencion) {
        this.retencion = retencion;
    }
    public double getSalarioNeto() {
        return this.salarioNeto;
    }
    
    public void setSalarioNeto(double salarioNeto) {
        this.salarioNeto = salarioNeto;
    }

    @Override
    public String toString() {
        return "Retenciones{" + "Empleado=" + id.getNombreEmpleado()  + ", Departamento=" + id.getNombreDepartamento()+ ", salarioBruto=" + salarioBruto + ", retencion=" + retencion + ", salarioNeto=" + salarioNeto + '}';
    }




}


