package POJOS;
// Generated 16-may-2024 21:23:39 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empleados generated by hbm2java
 */
public class Empleados  implements java.io.Serializable {


     private int empNo;
     private Departamentos departamentos;
     private Empleados empleados;
     private String apellido;
     private String oficio;
     private Date fechaAlt;
     private double salario;
     private double comision;
     private Set empleadoses = new HashSet(0);

    public Empleados() {
    }

	
    public Empleados(int empNo, Departamentos departamentos) {
        this.empNo = empNo;
        this.departamentos = departamentos;
    }
    public Empleados(int empNo, Departamentos departamentos, Empleados empleados, String apellido, String oficio, Date fechaAlt, double salario, double comision, Set empleadoses) {
       this.empNo = empNo;
       this.departamentos = departamentos;
       this.empleados = empleados;
       this.apellido = apellido;
       this.oficio = oficio;
       this.fechaAlt = fechaAlt;
       this.salario = salario;
       this.comision = comision;
       this.empleadoses = empleadoses;
    }

    public Empleados(int codigo, Departamentos departamento, Empleados dir, String apellido, String oficio, Date date, int salario, int comision) {
       this.empNo = codigo;
       this.departamentos = departamento;
       this.empleados = dir;
       this.apellido = apellido;
       this.oficio = oficio;
       this.fechaAlt = date;
       this.salario = salario;
       this.comision = comision;       
    }
   
    public int getEmpNo() {
        return this.empNo;
    }
    
    public void setEmpNo(int empNo) {
        this.empNo = empNo;
    }
    public Departamentos getDepartamentos() {
        return this.departamentos;
    }
    
    public void setDepartamentos(Departamentos departamentos) {
        this.departamentos = departamentos;
    }
    public Empleados getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Empleados empleados) {
        this.empleados = empleados;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getOficio() {
        return this.oficio;
    }
    
    public void setOficio(String oficio) {
        this.oficio = oficio;
    }
    public Date getFechaAlt() {
        return this.fechaAlt;
    }
    
    public void setFechaAlt(Date fechaAlt) {
        this.fechaAlt = fechaAlt;
    }
    public double getSalario() {
        return this.salario;
    }
    
    public void setSalario(double salario) {
        this.salario = salario;
    }
    public double getComision() {
        return this.comision;
    }
    
    public void setComision(double comision) {
        this.comision = comision;
    }
    public Set getEmpleadoses() {
        return this.empleadoses;
    }
    
    public void setEmpleadoses(Set empleadoses) {
        this.empleadoses = empleadoses;
    }

    @Override
    public String toString() {
        return "Empleados{" + "empNo=" + empNo + ", departamento=" + departamentos.getNombre() + ", empleados=" + empleados + ", apellido=" + apellido + ", oficio=" + oficio + ", fechaAlt=" + fechaAlt + ", salario=" + salario + ", comision=" + comision + '}';
    }




}


