package POJOS;
// Generated 19-may-2024 16:48:58 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private int codprod;
     private String nombre;
     private double precio;
     private Set ventases = new HashSet(0);

    public Productos() {
    }

	
    public Productos(int codprod) {
        this.codprod = codprod;
    }
    public Productos(int codprod, String nombre, double precio, Set ventases) {
       this.codprod = codprod;
       this.nombre = nombre;
       this.precio = precio;
       this.ventases = ventases;
    }
   
    public int getCodprod() {
        return this.codprod;
    }
    
    public void setCodprod(int codprod) {
        this.codprod = codprod;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }
    public Set getVentases() {
        return this.ventases;
    }
    
    public void setVentases(Set ventases) {
        this.ventases = ventases;
    }

    @Override
    public String toString() {
        return "Productos{" + "codprod=" + codprod + ", nombre=" + nombre + ", precio=" + precio + '}';
    }

}


