package POJOS;
// Generated 19-may-2024 16:48:58 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Ventas generated by hbm2java
 */
public class Ventas  implements java.io.Serializable {


     private int id;
     private Productos productos;
     private String codVend;
     private Integer unidades;
     private double ganancia;

    public Ventas() {
    }

	
    public Ventas(int id) {
        this.id = id;
    }
    public Ventas(int id, Productos productos, String codVend, Integer unidades, double ganancia) {
       this.id = id;
       this.productos = productos;
       this.codVend = codVend;
       this.unidades = unidades;
       this.ganancia = ganancia;
    }
    public Ventas(String codVend, Productos productos, Integer unidades) {
       this.productos = productos;
       this.codVend = codVend;
       this.unidades = unidades;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }
    public String getCodVend() {
        return this.codVend;
    }
    
    public void setCodVend(String codVend) {
        this.codVend = codVend;
    }
    public Integer getUnidades() {
        return this.unidades;
    }
    
    public void setUnidades(Integer unidades) {
        this.unidades = unidades;
    }
    public double getGanancia() {
        return this.ganancia;
    }
    
    public void setGanancia(double ganancia) {
        this.ganancia = ganancia;
    }

    @Override
    public String toString() {
        return "Ventas{" + "id=" + id + ", producto=" + productos.getNombre() + ", codVend=" + codVend + ", unidades=" + unidades + ", ganancia=" + ganancia + '}';
    }

}


