package POJOS;
// Generated 06-may-2024 12:06:01 by Hibernate Tools 4.3.1



/**
 * Localidades generated by hbm2java
 */
public class Localidades  implements java.io.Serializable {


     private String codLoc;
     private String nombre;
     private Integer censo;
     private Integer habitantes;
     private String nomProv;

    public Localidades() {
    }

	
    public Localidades(String codLoc, String nombre) {
        this.codLoc = codLoc;
        this.nombre = nombre;
    }
    public Localidades(String codLoc, String nombre, Integer censo, Integer habitantes, String nomProv) {
       this.codLoc = codLoc;
       this.nombre = nombre;
       this.censo = censo;
       this.habitantes = habitantes;
       this.nomProv = nomProv;
    }
   
    public String getCodLoc() {
        return this.codLoc;
    }
    
    public void setCodLoc(String codLoc) {
        this.codLoc = codLoc;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getCenso() {
        return this.censo;
    }
    
    public void setCenso(Integer censo) {
        this.censo = censo;
    }
    public Integer getHabitantes() {
        return this.habitantes;
    }
    
    public void setHabitantes(Integer habitantes) {
        this.habitantes = habitantes;
    }
    public String getNomProv() {
        return this.nomProv;
    }
    
    public void setNomProv(String nomProv) {
        this.nomProv = nomProv;
    }

    @Override
    public String toString() {
        return "Localidades{" + "codLoc=" + codLoc + ", nombre=" + nombre + ", censo=" + censo + ", habitantes=" + habitantes + ", nomProv=" + nomProv + '}';
    }

}


