package POJOS;
// Generated 02-may-2024 17:06:12 by Hibernate Tools 4.3.1



/**
 * Profesion generated by hbm2java
 */
public class Profesion  implements java.io.Serializable {


     private int id;
     private String nombre;

    public Profesion() {
    }

	
    public Profesion(int id) {
        this.id = id;
    }
    public Profesion(int id, String nombre) {
       this.id = id;
       this.nombre = nombre;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Override
    public String toString() {
        return "Profesion{" + "id=" + id + ", nombre=" + nombre + '}';
    }
    
}


